// ============================================================
// TRAVEL DESTINATIONS DATA
// Updated: April 15, 2026
// 27 European destinations + Morocco for study abroad students
// Organized by trip type and difficulty
// ============================================================

const travelDestinations = [
  // ============ LONDON (HOME BASE) ============
  {
    id: "london",
    name: "London",
    country: "England",
    coordinates: [-0.1278, 51.5074],
    marker_emoji: "🎭",
    image_url: "images/london.avif",
    description: "Your study abroad base - museums, markets, neighborhoods, and iconic sights.",
    budget: "expensive",
    estimated_cost: "£15–30/day",
    duration_category: "weekend",
    duration_label: "1–2 days",
    travel_time: "home",
    best_season: ["spring", "summer", "fall"],
    interests: ["culture", "food", "history", "nightlife", "art"],
    vibe: ["social", "cultural"],
    travel_style: ["cultural", "food-focused", "group-friendly"],
    priorities: ["best-museums", "best-nightlife", "easy-to-get-around"],
    weather: ["variable", "cool"],
    student_tip: "Free museum entries on certain days. Day trips are perfect for exploring new areas without traveling far.",
    highlights: ["British Museum", "Tower of London", "Markets", "Neighborhoods"],
    testimonial_source: "TCU Study Abroad",
    has_guide: true
  },

  // ============ EASY WEEKEND GETAWAYS ============
  {
    id: "bruges",
    name: "Bruges",
    country: "Belgium",
    coordinates: [3.2247, 51.2093],
    marker_emoji: "🏰",
    image_url: "images/bruges.jpg",
    description: "Fairytale medieval town - chocolate, beer, canals, and medieval magic.",
    budget: "moderate",
    estimated_cost: "£60–120",
    duration_category: "weekend",
    duration_label: "2 days",
    travel_time: "1.5 hours",
    best_season: ["spring", "summer", "fall"],
    interests: ["culture", "history", "food", "relaxation"],
    vibe: ["romantic", "cultural"],
    travel_style: ["cultural", "chill"],
    priorities: ["romantic", "best-food", "easy-to-get-around"],
    weather: ["mild", "pleasant"],
    student_tip: "Bruges is touristy but worth it. Rent a bike to escape crowds. Belgian waffles and chocolate everywhere.",
    highlights: ["Medieval Center", "Canals", "Chocolate Shops", "Belgian Waffles"],
    testimonial_source: "Fairytale Town"
  },

  {
    id: "paris",
    name: "Paris",
    country: "France",
    coordinates: [2.3522, 48.8566],
    marker_emoji: "🗼",
    image_url: "images/paris.jpeg",
    description: "The City of Light - iconic museums, cafés, and romantic architecture.",
    budget: "moderate",
    estimated_cost: "£80–150",
    duration_category: "weekend",
    duration_label: "2–3 days",
    travel_time: "2.5 hours",
    best_season: ["spring", "fall"],
    interests: ["art", "culture", "food", "romance"],
    vibe: ["romantic", "cultural"],
    travel_style: ["budget-friendly", "cultural"],
    priorities: ["best-museums", "best-food", "romantic"],
    weather: ["mild", "pleasant"],
    student_tip: "Buy a Paris Museum Pass if visiting multiple museums. Hostels in Latin Quarter are very social and budget-friendly.",
    highlights: ["Eiffel Tower", "Louvre Museum", "Cafés", "Seine River"],
    testimonial_source: "Sarah & Marcus",
    has_guide: true
  },

  {
    id: "amsterdam",
    name: "Amsterdam",
    country: "Netherlands",
    coordinates: [4.8945, 52.3676],
    marker_emoji: "🚲",
    image_url: "images/amsterdam.jpg",
    description: "Canals, bikes, and vibrant nightlife - very student-friendly.",
    budget: "budget",
    estimated_cost: "£70–130",
    duration_category: "weekend",
    duration_label: "2–3 days",
    travel_time: "3 hours",
    best_season: ["spring", "summer"],
    interests: ["nightlife", "culture", "food", "cycling"],
    vibe: ["social", "energetic"],
    travel_style: ["group-friendly", "budget-friendly"],
    priorities: ["best-nightlife", "easy-to-get-around", "social"],
    weather: ["cool", "variable"],
    student_tip: "Get a bike rental - it's the best way to explore. Free museums on certain hours.",
    highlights: ["Canal Cruises", "Anne Frank House", "Bike Culture", "Cafés"],
    testimonial_source: "Emma & Jamal"
  },

  {
    id: "dublin",
    name: "Dublin",
    country: "Ireland",
    coordinates: [-6.2603, 53.3498],
    marker_emoji: "🍺",
    image_url: "images/dublin.jpeg",
    description: "Temple Bar, literary history, and legendary Irish charm - easy access from London.",
    budget: "moderate",
    estimated_cost: "£60–120",
    duration_category: "weekend",
    duration_label: "2–3 days",
    travel_time: "1.5 hours (flight)",
    best_season: ["summer", "spring"],
    interests: ["nightlife", "culture", "food", "history"],
    vibe: ["social", "energetic"],
    travel_style: ["group-friendly", "adventure"],
    priorities: ["best-nightlife", "best-food", "social"],
    weather: ["cool", "variable"],
    student_tip: "Book Temple Bar early - it fills up fast. Guinness Storehouse is worth the entry for the views.",
    highlights: ["Temple Bar", "Trinity College", "Guinness Storehouse", "Pubs"],
    testimonial_source: "Group Travel Favorite",
    has_guide: true
  },

  {
    id: "prague",
    name: "Prague",
    country: "Czech Republic",
    coordinates: [14.4370, 50.0755],
    marker_emoji: "🏰",
    image_url: "images/prague.jpg",
    description: "Medieval fairytale city - stunning architecture and very cheap.",
    budget: "budget",
    estimated_cost: "£50–100",
    duration_category: "weekend",
    duration_label: "2–3 days",
    travel_time: "2 hours (flight)",
    best_season: ["spring", "fall"],
    interests: ["history", "architecture", "food", "culture"],
    vibe: ["romantic", "cultural"],
    travel_style: ["budget-friendly", "cultural"],
    priorities: ["best-budget", "romantic", "easy-to-get-around"],
    weather: ["mild", "pleasant"],
    student_tip: "Czech beer is incredibly cheap - enjoy it! Avoid Old Town Square restaurants, head to side streets.",
    highlights: ["Charles Bridge", "Prague Castle", "Old Town Square", "Beer Halls"],
    testimonial_source: "Jamal & Liv",
    has_guide: true
  },

  {
    id: "budapest",
    name: "Budapest",
    country: "Hungary",
    coordinates: [19.0402, 47.4979],
    marker_emoji: "🛁",
    image_url: "images/budapest.webp",
    description: "Thermal baths and ruin bars - perfect for a fun, affordable weekend.",
    budget: "budget",
    estimated_cost: "£50–110",
    duration_category: "weekend",
    duration_label: "2–3 days",
    travel_time: "2.5 hours (flight)",
    best_season: ["spring", "summer", "fall"],
    interests: ["nightlife", "relaxation", "culture", "food"],
    vibe: ["social", "relaxed"],
    travel_style: ["group-friendly", "wellness"],
    priorities: ["best-nightlife", "best-value", "social"],
    weather: ["warm", "pleasant"],
    student_tip: "Ruin bars are iconic - extremely social. Thermal baths are therapeutic and cheap.",
    highlights: ["Thermal Baths", "Ruin Bars", "Danube River", "Street Food"],
    testimonial_source: "Aiden & Kai",
    has_guide: true
  },

  {
    id: "krakow",
    name: "Kraków",
    country: "Poland",
    coordinates: [19.9450, 50.0647],
    marker_emoji: "⛓️",
    image_url: "images/krakow.jpeg",
    description: "Historic city with medieval charm, proximity to salt mines, and vibrant student scene.",
    budget: "budget",
    estimated_cost: "£40–90",
    duration_category: "weekend",
    duration_label: "2–3 days",
    travel_time: "2.5 hours (flight)",
    best_season: ["spring", "fall"],
    interests: ["history", "culture", "nightlife", "food"],
    vibe: ["cultural", "social"],
    travel_style: ["budget-friendly", "cultural"],
    priorities: ["best-budget", "best-nightlife", "easy-to-get-around"],
    weather: ["cool", "pleasant"],
    student_tip: "Kazimierz is the heart of student nightlife. The salt mines are a unique day trip.",
    highlights: ["Main Square", "Kazimierz District", "Salt Mines", "Street Food"],
    testimonial_source: "Polish Adventure"
  },

  {
    id: "edinburgh",
    name: "Edinburgh",
    country: "Scotland",
    coordinates: [-3.1883, 55.9533],
    marker_emoji: "🥃",
    image_url: "images/edinburugh.avif",
    description: "Medieval castles, cobbled streets, and stunning Scottish views.",
    budget: "moderate",
    estimated_cost: "£50–100",
    duration_category: "weekend",
    duration_label: "2–3 days",
    travel_time: "2 hours (flight or train)",
    best_season: ["summer", "fall"],
    interests: ["history", "culture", "hiking", "nightlife"],
    vibe: ["cultural", "energetic"],
    travel_style: ["cultural", "adventure"],
    priorities: ["best-views", "easy-to-get-around", "romantic"],
    weather: ["cool", "variable"],
    student_tip: "Stay in the city center for access to everything. The walk up to Edinburgh Castle is worth the effort.",
    highlights: ["Edinburgh Castle", "Royal Mile", "Holyrood Park", "Nightlife"],
    testimonial_source: "UK Trip Favorite"
  },

  {
    id: "malta",
    name: "Malta",
    country: "Malta",
    coordinates: [14.5898, 35.9375],
    marker_emoji: "🌊",
    image_url: "images/malta.webp",
    description: "Ancient ruins, turquoise water, and Mediterranean charm in a tiny island nation.",
    budget: "moderate",
    estimated_cost: "£70–140",
    duration_category: "weekend",
    duration_label: "2–3 days",
    travel_time: "2.5 hours (flight)",
    best_season: ["spring", "summer", "fall"],
    interests: ["history", "beach", "culture", "diving"],
    vibe: ["relaxed", "social"],
    travel_style: ["adventure", "chill"],
    priorities: ["best-beach", "best-history", "easy-to-get-around"],
    weather: ["warm", "sunny"],
    student_tip: "Valletta is the historic capital. The tiny size means everything is walkable. Great diving spot.",
    highlights: ["Valletta", "Blue Lagoon", "Ancient Temples", "Diving"],
    testimonial_source: "Mediterranean Gem"
  },

  // ============ BEACH & WARM WEATHER TRIPS ============
  {
    id: "barcelona",
    name: "Barcelona",
    country: "Spain",
    coordinates: [2.1729, 41.3851],
    marker_emoji: "🏖️",
    image_url: "images/barcelona.jpg",
    description: "Beach, architecture, and vibrant culture - perfect for spring/summer.",
    budget: "moderate",
    estimated_cost: "£100–180",
    duration_category: "extended",
    duration_label: "3–4 days",
    travel_time: "2 hours (flight)",
    best_season: ["spring", "summer", "fall"],
    interests: ["beach", "architecture", "food", "culture"],
    vibe: ["energetic", "social"],
    travel_style: ["group-friendly", "adventure"],
    priorities: ["best-food", "best-nightlife", "easy-to-get-around"],
    weather: ["warm", "sunny"],
    student_tip: "Visit Sagrada Familia early or buy skip-the-line tickets. Beachfront drinks are pricier than city center.",
    highlights: ["Sagrada Familia", "Park Güell", "Beach", "Tapas"],
    testimonial_source: "Zara & Marcus"
  },

  {
    id: "madrid",
    name: "Madrid",
    country: "Spain",
    coordinates: [-3.7038, 40.4168],
    marker_emoji: "🎨",
    image_url: "images/madrid.jpeg",
    description: "Spain's energetic capital - world-class museums, tapas, and late-night vibes.",
    budget: "moderate",
    estimated_cost: "£70–140",
    duration_category: "extended",
    duration_label: "2–3 days",
    travel_time: "2 hours (flight)",
    best_season: ["spring", "fall"],
    interests: ["food", "art", "nightlife", "culture"],
    vibe: ["energetic", "social"],
    travel_style: ["group-friendly", "food-focused"],
    priorities: ["best-museums", "best-nightlife", "best-food"],
    weather: ["warm", "sunny"],
    student_tip: "Dinner starts late (9pm+). Free museum hours are 6–8pm weekdays. Tapas crawl in La Latina.",
    highlights: ["Prado Museum", "La Latina", "Retiro Park", "Tapas Bars"],
    testimonial_source: "Spain's Capital"
  },

  {
    id: "lisbon",
    name: "Lisbon",
    country: "Portugal",
    coordinates: [-9.1393, 38.7223],
    marker_emoji: "☀️",
    image_url: "images/lisbon.webp",
    description: "Warm weather, friendly locals, and great food - Portugal's coolest city.",
    budget: "budget",
    estimated_cost: "£60–120",
    duration_category: "extended",
    duration_label: "3 days",
    travel_time: "3 hours (flight)",
    best_season: ["spring", "summer", "fall"],
    interests: ["beach", "food", "culture", "relaxation"],
    vibe: ["relaxed", "social"],
    travel_style: ["budget-friendly", "chill"],
    priorities: ["best-food", "best-weather", "budget"],
    weather: ["warm", "sunny"],
    student_tip: "Pastel de Nata and cheap wine everywhere. The city is very walkable and affordable.",
    highlights: ["Belém Tower", "Street Food", "Fado Music", "Beaches"],
    testimonial_source: "Emma & Nia",
    has_guide: true
  },

  {
    id: "porto",
    name: "Porto",
    country: "Portugal",
    coordinates: [-8.6291, 41.1579],
    marker_emoji: "🍷",
    image_url: "images/porto.webp",
    description: "Portugal's hidden gem - riverside charm, Port wine, and historic neighborhoods.",
    budget: "budget",
    estimated_cost: "£50–100",
    duration_category: "weekend",
    duration_label: "2–3 days",
    travel_time: "3.5 hours (flight)",
    best_season: ["spring", "summer", "fall"],
    interests: ["food", "culture", "relaxation", "wine"],
    vibe: ["relaxed", "cultural"],
    travel_style: ["budget-friendly", "chill"],
    priorities: ["best-food", "best-value", "easy-to-get-around"],
    weather: ["warm", "pleasant"],
    student_tip: "Stay in Ribeira for authentic vibes. Port wine tastings are a must - find affordable tasting rooms.",
    highlights: ["Ribeira District", "Dom Luís Bridge", "Port Wine", "River Cruises"],
    testimonial_source: "Hidden Gem"
  },

  {
    id: "valencia",
    name: "Valencia",
    country: "Spain",
    coordinates: [-0.3763, 39.4699],
    marker_emoji: "🥘",
    image_url: "images/valencia.jpeg",
    description: "Beach vibes with futuristic architecture, paella, and less touristy than Barcelona.",
    budget: "moderate",
    estimated_cost: "£70–130",
    duration_category: "extended",
    duration_label: "2–3 days",
    travel_time: "2.5 hours (flight)",
    best_season: ["spring", "summer", "fall"],
    interests: ["beach", "architecture", "food", "culture"],
    vibe: ["energetic", "relaxed"],
    travel_style: ["group-friendly", "food-focused"],
    priorities: ["best-food", "best-beach", "easy-to-get-around"],
    weather: ["warm", "sunny"],
    student_tip: "City of Arts and Sciences is stunning. Paella is authentic here and way cheaper than tourist spots.",
    highlights: ["City of Arts & Sciences", "Beach", "Paella", "Las Fallas (March)"],
    testimonial_source: "Beach Alternative"
  },

  {
    id: "mallorca",
    name: "Mallorca",
    country: "Spain",
    coordinates: [2.7500, 39.5500],
    marker_emoji: "🏝️",
    image_url: "images/mallorca.jpg",
    description: "Balearic island perfection - beaches, mountain views, and party culture.",
    budget: "moderate",
    estimated_cost: "£100–180",
    duration_category: "extended",
    duration_label: "3–4 days",
    travel_time: "2 hours (flight)",
    best_season: ["summer"],
    interests: ["beach", "nightlife", "food", "nature"],
    vibe: ["energetic", "social"],
    travel_style: ["group-friendly", "adventure"],
    priorities: ["best-nightlife", "best-beach", "social"],
    weather: ["warm", "sunny"],
    student_tip: "Avoid Magaluf if you want authentic vibes. Palma is way better for culture and food.",
    highlights: ["Beaches", "Nightlife", "Mountain Hikes", "Fresh Seafood"],
    testimonial_source: "Island Paradise"
  },

  {
    id: "tenerife",
    name: "Tenerife",
    country: "Spain (Canary Islands)",
    coordinates: [-16.3387, 28.2916],
    marker_emoji: "🌋",
    image_url: "images/tenerife.webp",
    description: "Canary Islands sunshine - beaches, volcanic landscape, and eternal summer.",
    budget: "moderate",
    estimated_cost: "£80–150",
    duration_category: "extended",
    duration_label: "3–5 days",
    travel_time: "4 hours (flight)",
    best_season: ["spring", "summer", "fall"],
    interests: ["beach", "hiking", "relaxation", "nature"],
    vibe: ["relaxed", "energetic"],
    travel_style: ["adventure", "chill"],
    priorities: ["best-weather", "best-beach", "best-value"],
    weather: ["warm", "sunny"],
    student_tip: "Climb Mount Teide at sunrise. Northern beaches are less touristy and cheaper than southern ones.",
    highlights: ["Mount Teide", "Black Sand Beaches", "Hiking", "Whale Watching"],
    testimonial_source: "Island Escape"
  },

  {
    id: "nice",
    name: "Nice",
    country: "France",
    coordinates: [7.2620, 43.7102],
    marker_emoji: "🌴",
    image_url: "images/nice.webp",
    description: "French Riviera elegance - beaches, promenade, and art scene.",
    budget: "expensive",
    estimated_cost: "£90–160",
    duration_category: "weekend",
    duration_label: "2–3 days",
    travel_time: "2.5 hours (flight)",
    best_season: ["spring", "summer", "fall"],
    interests: ["beach", "art", "food", "relaxation"],
    vibe: ["relaxed", "cultural"],
    travel_style: ["food-focused", "chill"],
    priorities: ["best-beach", "best-food", "best-views"],
    weather: ["warm", "sunny"],
    student_tip: "Promenade des Anglais is perfect for people-watching. Explore the Old Town for authentic restaurants.",
    highlights: ["Promenade des Anglais", "Old Town", "Beaches", "Art Museums"],
    testimonial_source: "Riviera Escape"
  },

  // ============ MOUNTAIN & SCENIC ADVENTURES ============
  {
    id: "interlaken",
    name: "Interlaken",
    country: "Switzerland",
    coordinates: [8.1792, 46.6863],
    marker_emoji: "⛰️",
    image_url: "images/interlaken.jpg",
    description: "Alpine paradise - mountain hikes, adventure sports, and jaw-dropping views.",
    budget: "expensive",
    estimated_cost: "£120–220",
    duration_category: "extended",
    duration_label: "2–3 days",
    travel_time: "2.5 hours (flight/train)",
    best_season: ["summer", "fall"],
    interests: ["hiking", "adventure", "nature", "mountain"],
    vibe: ["adventurous", "energetic"],
    travel_style: ["adventure", "nature"],
    priorities: ["best-views", "best-hiking", "adventure"],
    weather: ["cool", "pleasant"],
    student_tip: "Book the Jungfrau train in advance for discounts. Budget hostels here are still pricey but worth it.",
    highlights: ["Jungfrau", "Mountain Hikes", "Adventure Sports", "Swiss Lakes"],
    testimonial_source: "Mountain Adventure"
  },

  {
    id: "lake-bled",
    name: "Lake Bled",
    country: "Slovenia",
    coordinates: [14.1122, 46.3625],
    marker_emoji: "💙",
    image_url: "images/lakebled.jpeg",
    description: "Stunning lake with island church - Slovenia's most romantic destination.",
    budget: "budget",
    estimated_cost: "£50–100",
    duration_category: "weekend",
    duration_label: "2–3 days",
    travel_time: "2 hours (flight)",
    best_season: ["summer", "spring"],
    interests: ["nature", "hiking", "romance", "relaxation"],
    vibe: ["relaxed", "romantic"],
    travel_style: ["chill", "nature"],
    priorities: ["best-views", "romantic", "budget"],
    weather: ["warm", "pleasant"],
    student_tip: "Row out to Bled Island in a traditional boat. The viewpoint hike is free and stunning.",
    highlights: ["Bled Island", "Castle Viewpoint", "Lake Hikes", "Cream Cake"],
    testimonial_source: "Hidden Gem"
  },

  {
    id: "dolomites",
    name: "Dolomites",
    country: "Italy",
    coordinates: [11.8500, 46.3000],
    marker_emoji: "🏔️",
    image_url: "images/dolomites.jpeg",
    description: "Dramatic mountain scenery - world-class hiking and postcard-perfect villages.",
    budget: "expensive",
    estimated_cost: "£100–180",
    duration_category: "extended",
    duration_label: "3–4 days",
    travel_time: "3 hours (flight)",
    best_season: ["summer", "fall"],
    interests: ["hiking", "nature", "mountain", "adventure"],
    vibe: ["adventurous", "energetic"],
    travel_style: ["adventure", "nature"],
    priorities: ["best-hiking", "best-views", "adventure"],
    weather: ["cool", "pleasant"],
    student_tip: "Book accommodation in villages like Cortina. Hiking the Tre Cime is iconic and worth it.",
    highlights: ["Tre Cime", "Mountain Hikes", "Alpine Villages", "Alpine Lakes"],
    testimonial_source: "Mountain Paradise"
  },

  {
    id: "cinque-terre",
    name: "Cinque Terre",
    country: "Italy",
    coordinates: [9.6833, 43.1333],
    marker_emoji: "🌅",
    image_url: "images/cinque terre.jpeg",
    description: "Five colorful cliff-hanging villages - UNESCO wonder and Italy's best hiking.",
    budget: "moderate",
    estimated_cost: "£80–150",
    duration_category: "extended",
    duration_label: "2–3 days",
    travel_time: "2.5 hours (flight/train)",
    best_season: ["spring", "summer", "fall"],
    interests: ["hiking", "nature", "food", "beach"],
    vibe: ["adventurous", "relaxed"],
    travel_style: ["adventure", "nature"],
    priorities: ["best-hiking", "best-views", "easy-to-get-around"],
    weather: ["warm", "pleasant"],
    student_tip: "Buy a 5-day Cinque Terre card for trains and trails. Stay in one village and day-hop by train.",
    highlights: ["Coastal Hikes", "Colorful Villages", "Fresh Seafood", "Swimming"],
    testimonial_source: "Italian Gem"
  },

  // ============ HISTORIC & CULTURE DESTINATIONS ============
  {
    id: "rome",
    name: "Rome",
    country: "Italy",
    coordinates: [12.4964, 41.9028],
    marker_emoji: "🏛️",
    image_url: "images/rome.webp",
    description: "Ancient history and amazing food - the ultimate student bucket list.",
    budget: "moderate",
    estimated_cost: "£90–160",
    duration_category: "extended",
    duration_label: "3–4 days",
    travel_time: "2.5 hours (flight)",
    best_season: ["spring", "fall"],
    interests: ["history", "food", "culture", "architecture"],
    vibe: ["historic", "cultural"],
    travel_style: ["cultural", "food-focused"],
    priorities: ["best-food", "best-museums", "romantic"],
    weather: ["warm", "pleasant"],
    student_tip: "Get the Roma Pass for museum entry. Street food (panini, pizza al taglio) is affordable.",
    highlights: ["Colosseum", "Vatican", "Roman Forum", "Gelato"],
    testimonial_source: "Marcus & Diego"
  },

  {
    id: "berlin",
    name: "Berlin",
    country: "Germany",
    coordinates: [13.4050, 52.5200],
    marker_emoji: "🎭",
    image_url: "images/berlin.avif",
    description: "History, street art, and legendary nightlife - very affordable.",
    budget: "budget",
    estimated_cost: "£60–120",
    duration_category: "extended",
    duration_label: "3 days",
    travel_time: "1.5 hours (flight)",
    best_season: ["spring", "fall"],
    interests: ["history", "nightlife", "art", "culture"],
    vibe: ["artsy", "social"],
    travel_style: ["budget-friendly", "cultural"],
    priorities: ["best-nightlife", "best-art-scene", "budget"],
    weather: ["cool", "pleasant"],
    student_tip: "Berlin is super affordable. Visit museums on free entry evenings. Kreuzberg has the best street art.",
    highlights: ["Brandenburg Gate", "Street Art", "Nightclubs", "Museums"],
    testimonial_source: "Sarah & Aiden"
  },

  {
    id: "vienna",
    name: "Vienna",
    country: "Austria",
    coordinates: [16.3738, 48.2082],
    marker_emoji: "🎼",
    image_url: "images/vienna.webp",
    description: "Imperial palaces, classical music, and elegant Austro-Hungarian architecture.",
    budget: "moderate",
    estimated_cost: "£60–120",
    duration_category: "extended",
    duration_label: "2–3 days",
    travel_time: "2.5 hours (flight)",
    best_season: ["spring", "fall"],
    interests: ["culture", "history", "food", "art"],
    vibe: ["cultural", "romantic"],
    travel_style: ["cultural", "food-focused"],
    priorities: ["best-museums", "romantic", "best-food"],
    weather: ["mild", "pleasant"],
    student_tip: "Get a Vienna City Card for free transport and museum discounts. Coffee culture is huge here.",
    highlights: ["Schönbrunn Palace", "St. Stephen's Cathedral", "Opera House", "Cafés"],
    testimonial_source: "Austria Visit"
  },

  {
    id: "copenhagen",
    name: "Copenhagen",
    country: "Denmark",
    coordinates: [12.5683, 55.6761],
    marker_emoji: "🚴",
    image_url: "images/copenhagen.webp",
    description: "Hygge vibes, colorful Nyhavn harbor, and cool Scandinavian design scene.",
    budget: "expensive",
    estimated_cost: "£70–150",
    duration_category: "weekend",
    duration_label: "2–3 days",
    travel_time: "1.5 hours (flight)",
    best_season: ["summer", "spring"],
    interests: ["design", "food", "nightlife", "culture"],
    vibe: ["social", "trendy"],
    travel_style: ["group-friendly", "adventure"],
    priorities: ["best-design", "best-food", "easy-to-get-around"],
    weather: ["cool", "pleasant"],
    student_tip: "Copenhagen is pricey but worth it. Bikes are the main transport. Visit Nyhavn at sunset.",
    highlights: ["Nyhavn Harbor", "Tivoli Gardens", "Street Food", "Design Scene"],
    testimonial_source: "Nordic Trip"
  },

  // ============ HIDDEN GEMS & UNIQUE DESTINATIONS ============
  {
    id: "chefchaouen",
    name: "Chefchaouen",
    country: "Morocco",
    coordinates: [-5.2698, 35.1684],
    marker_emoji: "🔵",
    image_url: "images/Chefchaouen.jpg",
    description: "Morocco's blue city - stunning Rif mountain scenery, culture, and adventure.",
    budget: "budget",
    estimated_cost: "£40–80",
    duration_category: "extended",
    duration_label: "3–4 days",
    travel_time: "3.5 hours (flight to Fez + transport)",
    best_season: ["spring", "fall"],
    interests: ["culture", "photography", "hiking", "adventure"],
    vibe: ["adventurous", "cultural"],
    travel_style: ["adventure", "cultural"],
    priorities: ["best-views", "best-budget", "adventure"],
    weather: ["warm", "pleasant"],
    student_tip: "Take the bus from Fez - it's an adventure in itself. Stay in a riad for authentic experiences.",
    highlights: ["Blue City Streets", "Rif Mountains", "Waterfalls", "Local Markets"],
    testimonial_source: "North Africa Adventure"
  },

  {
    id: "marrakech",
    name: "Marrakech",
    country: "Morocco",
    coordinates: [-8.0029, 31.6295],
    marker_emoji: "🌙",
    image_url: "images/Marrakech.jpg",
    description: "Morocco's magic city - bustling medinas, palaces, and Sahara desert access.",
    budget: "budget",
    estimated_cost: "£50–100",
    duration_category: "extended",
    duration_label: "3–4 days",
    travel_time: "3.5 hours (flight)",
    best_season: ["spring", "fall"],
    interests: ["culture", "food", "history", "adventure"],
    vibe: ["energetic", "cultural"],
    travel_style: ["adventure", "cultural", "food-focused"],
    priorities: ["best-culture", "best-budget", "adventure"],
    weather: ["warm", "sunny"],
    student_tip: "Jemaa el-Fnaa square is chaotic but essential. Take a day trip to the Atlas Mountains or Sahara.",
    highlights: ["Medina", "Jemaa el-Fnaa", "Palaces", "Atlas Mountains"],
    testimonial_source: "Morocco Escape"
  },

  {
    id: "sicily",
    name: "Sicily",
    country: "Italy",
    coordinates: [14.0055, 37.7412],
    marker_emoji: "🌋",
    image_url: "images/Sicily.avif",
    description: "Italy's island gem - ancient ruins, stunning beaches, and unique Mediterranean culture.",
    budget: "moderate",
    estimated_cost: "£80–150",
    duration_category: "extended",
    duration_label: "3–4 days",
    travel_time: "2.5 hours (flight)",
    best_season: ["spring", "summer", "fall"],
    interests: ["culture", "history", "food", "beach", "art"],
    vibe: ["romantic", "cultural", "relaxed"],
    travel_style: ["cultural", "food-focused", "adventure"],
    priorities: ["best-food", "best-culture", "best-views"],
    weather: ["warm", "sunny"],
    student_tip: "Less touristy than mainland Italy. Boat tours through sea caves are unforgettable. Try local street food.",
    highlights: ["Ortigia Island", "Mount Etna", "Sea Caves", "Local Markets", "Beaches"],
    testimonial_source: "Sicily Adventure"
  },

  {
    id: "florence",
    name: "Florence",
    country: "Italy",
    coordinates: [11.2558, 43.7696],
    marker_emoji: "🍝",
    image_url: "images/Florence.jpeg",
    description: "The Renaissance capital - art museums, historic architecture, and culinary excellence.",
    budget: "expensive",
    estimated_cost: "£120–180",
    duration_category: "extended",
    duration_label: "2–3 days",
    travel_time: "2 hours (flight)",
    best_season: ["spring", "fall"],
    interests: ["art", "history", "culture", "food"],
    vibe: ["cultural", "romantic", "artsy"],
    travel_style: ["cultural", "food-focused"],
    priorities: ["best-museums", "romantic", "best-food"],
    weather: ["mild", "pleasant"],
    student_tip: "The city is walkable and starts to feel like home. Book museums in advance. Early mornings avoid crowds.",
    highlights: ["Uffizi Gallery", "Duomo", "Arno River", "Local Bakeries", "Neighborhoods"],
    testimonial_source: "Florence Study",
    has_guide: true
  },

  {
    id: "mount-etna",
    name: "Mount Etna",
    country: "Italy",
    coordinates: [15.0038, 37.7412],
    marker_emoji: "🌋",
    image_url: "images/Mount Etna.jpg",
    description: "Europe's most active volcano - dramatic landscapes, local wine, and unforgettable views.",
    budget: "moderate",
    estimated_cost: "£60–120",
    duration_category: "weekend",
    duration_label: "1–2 days",
    travel_time: "2.5 hours (from Palermo)",
    best_season: ["spring", "summer", "fall"],
    interests: ["adventure", "nature", "photography", "history"],
    vibe: ["adventurous", "scenic"],
    travel_style: ["adventure", "nature"],
    priorities: ["best-views", "adventure", "best-hiking"],
    weather: ["warm", "sunny"],
    student_tip: "Boat tours around the volcano are incredible. Try local wine from slopes. Go early to avoid crowds.",
    highlights: ["Volcano Crater", "Local Wine", "Scenic Views", "Boat Tours"],
    testimonial_source: "Sicily Nature"
  }
];

// ============================================================
// COLOR & EMOJI MAPPING FOR FILTERS
// ============================================================

const budgetColors = {
  "budget": "#2ecc71",
  "moderate": "#f39c12",
  "expensive": "#e74c3c"
};

const vibeEmojis = {
  "romantic": "💕",
  "social": "🎉",
  "energetic": "⚡",
  "artsy": "🎨",
  "historic": "📚",
  "relaxed": "😌",
  "cultural": "🌍",
  "adventurous": "🧗",
  "trendy": "✨"
};

// ============================================================
// STUDENT TESTIMONIALS
// ============================================================

const studentTestimonials = [
  {
    id: "grace-rome",
    name: "Grace Allen",
    avatar: "🇮🇹",
    home_base_city: "Rome",
    country: "Italy",
    term: "Summer 2025",
    program: "Accent Global",
    short_quote: "It still doesn't feel real that I got to live there.",
    cost_reality: "More expensive than expected",
    ease_of_travel: 4,
    budget_tip: "Pack smarter and bring more basics so you don't waste money rebuying things abroad.",
    favorite_thing: "You'll randomly walk past historic landmarks just exploring the city.",
    favorite_food: "",
    favorite_activity: "Seeing the Trevi Fountain",
    favorite_trip: "Cinque Terre",
    testimonial_takeaway: "The best part was experiencing everything with my friends.",
    destination_link: "rome",
    favorite_trip_link: "cinque-terre"
  },
  {
    id: "keira-sicily",
    name: "Keira Brown",
    avatar: "🌋",
    home_base_city: "Sicily",
    country: "Italy",
    term: "June 2024",
    program: "Accent Global",
    short_quote: "Sicily ended up being way more meaningful than I expected.",
    cost_reality: "About what I expected, but food spending added up",
    ease_of_travel: 5,
    budget_tip: "Cook more meals at home and understand exchange rates before you go.",
    favorite_thing: "Less touristy and more culturally immersive than other Italian cities.",
    favorite_food: "Fratelli Burgio (Ortigia Market)",
    favorite_activity: "Boat tour through caves",
    favorite_trip: "Mount Etna",
    testimonial_takeaway: "It felt like a deeper cultural experience, not just a trip.",
    destination_link: "sicily",
    favorite_trip_link: "mount-etna"
  },
  {
    id: "abby-florence",
    name: "Abby Lohmann",
    avatar: "🍝",
    home_base_city: "Florence",
    country: "Italy",
    term: "Spring 2026",
    program: "Accent Global",
    short_quote: "I genuinely don't want this to end.",
    cost_reality: "About what I expected, but small costs add up quickly",
    ease_of_travel: 5,
    budget_tip: "Stay on top of spending—things like water and small purchases add up fast.",
    favorite_thing: "The city is so walkable it starts to feel like home.",
    favorite_food: "Wild Buns Bakery, Simbiosi",
    favorite_activity: "Walking along the river",
    favorite_trip: "Mallorca",
    testimonial_takeaway: "It feels like living there, not just visiting.",
    destination_link: "florence",
    favorite_trip_link: "mallorca"
  },
  {
    id: "sarah-barcelona",
    name: "Sarah Hogan",
    avatar: "🏖️",
    home_base_city: "Barcelona",
    country: "Spain",
    term: "Fall 2024",
    program: "Direct Exchange",
    short_quote: "There was always something going on.",
    cost_reality: "About what I expected",
    ease_of_travel: 5,
    budget_tip: "Compare Airbnbs, hotels, and hostels—cheapest option changes by city.",
    favorite_thing: "You're never bored—there's always something to do.",
    favorite_food: "Good News Coffee, Bo de Be, La Pachuca, Sensi Tapas",
    favorite_activity: "Beach days and exploring the Gothic Quarter",
    favorite_trip: "Dolomites",
    testimonial_takeaway: "The energy, culture, and people made it unforgettable.",
    destination_link: "barcelona",
    favorite_trip_link: "dolomites"
  },
  {
    id: "annie-sas",
    name: "Annie Raso",
    avatar: "🌍",
    home_base_city: "Semester at Sea",
    country: "Multiple Countries",
    term: "Global Program",
    program: "Semester at Sea",
    short_quote: "It completely changed me.",
    cost_reality: "More expensive than expected",
    ease_of_travel: null,
    budget_tip: "Travel with people who have a similar budget to avoid overspending.",
    favorite_thing: "Being disconnected from WiFi made the experience more meaningful.",
    favorite_food: "",
    favorite_activity: "Relaxing on deck between classes",
    favorite_trip: "Kenya",
    testimonial_takeaway: "It changed my perspective on the world and myself.",
    destination_link: "semester-at-sea",
    favorite_trip_link: "kenya"
  }
];
