// ============================================================
// TRAVEL DESTINATIONS DATA
// Updated: April 15, 2026
// 27 European destinations + Morocco for study abroad students
// Organized by trip type and difficulty
// ============================================================

const travelDestinations = [
  // ============ LONDON (HOME BASE) ============
  {
    id: "london",
    name: "London",
    country: "England",
    coordinates: [-0.1278, 51.5074],
    marker_emoji: "🎭",
    image_url: "https://images.unsplash.com/photo-1513635269975-59663e0ac1ad?w=400&h=300&fit=crop",
    description: "Your study abroad base - museums, markets, neighborhoods, and iconic sights.",
    budget: "expensive",
    estimated_cost: "£15–30/day",
    duration_category: "weekend",
    duration_label: "1–2 days",
    travel_time: "home",
    best_season: ["spring", "summer", "fall"],
    interests: ["culture", "food", "history", "nightlife", "art"],
    vibe: ["social", "cultural"],
    travel_style: ["cultural", "food-focused", "group-friendly"],
    priorities: ["best-museums", "best-nightlife", "easy-to-get-around"],
    weather: ["variable", "cool"],
    student_tip: "Free museum entries on certain days. Day trips are perfect for exploring new areas without traveling far.",
    highlights: ["British Museum", "Tower of London", "Markets", "Neighborhoods"],
    testimonial_source: "TCU Study Abroad"
  },

  // ============ EASY WEEKEND GETAWAYS ============
  {
    id: "bruges",
    name: "Bruges",
    country: "Belgium",
    coordinates: [3.2247, 51.2093],
    marker_emoji: "🏰",
    image_url: "https://images.unsplash.com/photo-1506905925346-21bda4d32df4?w=400&h=300&fit=crop",
    description: "Fairytale medieval town - chocolate, beer, canals, and medieval magic.",
    budget: "moderate",
    estimated_cost: "£60–120",
    duration_category: "weekend",
    duration_label: "2 days",
    travel_time: "1.5 hours",
    best_season: ["spring", "summer", "fall"],
    interests: ["culture", "history", "food", "relaxation"],
    vibe: ["romantic", "cultural"],
    travel_style: ["cultural", "chill"],
    priorities: ["romantic", "best-food", "easy-to-get-around"],
    weather: ["mild", "pleasant"],
    student_tip: "Bruges is touristy but worth it. Rent a bike to escape crowds. Belgian waffles and chocolate everywhere.",
    highlights: ["Medieval Center", "Canals", "Chocolate Shops", "Belgian Waffles"],
    testimonial_source: "Fairytale Town"
  },

  {
    id: "paris",
    name: "Paris",
    country: "France",
    coordinates: [2.3522, 48.8566],
    marker_emoji: "🗼",
    image_url: "https://images.unsplash.com/photo-1502602898657-3e91760cbb34?w=400&h=300&fit=crop",
    description: "The City of Light - iconic museums, cafés, and romantic architecture.",
    budget: "moderate",
    estimated_cost: "£80–150",
    duration_category: "weekend",
    duration_label: "2–3 days",
    travel_time: "2.5 hours",
    best_season: ["spring", "fall"],
    interests: ["art", "culture", "food", "romance"],
    vibe: ["romantic", "cultural"],
    travel_style: ["budget-friendly", "cultural"],
    priorities: ["best-museums", "best-food", "romantic"],
    weather: ["mild", "pleasant"],
    student_tip: "Buy a Paris Museum Pass if visiting multiple museums. Hostels in Latin Quarter are very social and budget-friendly.",
    highlights: ["Eiffel Tower", "Louvre Museum", "Cafés", "Seine River"],
    testimonial_source: "Sarah & Marcus"
  },

  {
    id: "amsterdam",
    name: "Amsterdam",
    country: "Netherlands",
    coordinates: [4.8945, 52.3676],
    marker_emoji: "🚲",
    image_url: "https://images.unsplash.com/photo-1517159135251-a63c35e15738?w=400&h=300&fit=crop",
    description: "Canals, bikes, and vibrant nightlife - very student-friendly.",
    budget: "budget",
    estimated_cost: "£70–130",
    duration_category: "weekend",
    duration_label: "2–3 days",
    travel_time: "3 hours",
    best_season: ["spring", "summer"],
    interests: ["nightlife", "culture", "food", "cycling"],
    vibe: ["social", "energetic"],
    travel_style: ["group-friendly", "budget-friendly"],
    priorities: ["best-nightlife", "easy-to-get-around", "social"],
    weather: ["cool", "variable"],
    student_tip: "Get a bike rental - it's the best way to explore. Free museums on certain hours.",
    highlights: ["Canal Cruises", "Anne Frank House", "Bike Culture", "Cafés"],
    testimonial_source: "Emma & Jamal"
  },

  {
    id: "dublin",
    name: "Dublin",
    country: "Ireland",
    coordinates: [-6.2603, 53.3498],
    marker_emoji: "🍺",
    image_url: "https://images.unsplash.com/photo-1526004913191-ff06b474b850?w=400&h=300&fit=crop",
    description: "Temple Bar, literary history, and legendary Irish charm - easy access from London.",
    budget: "moderate",
    estimated_cost: "£60–120",
    duration_category: "weekend",
    duration_label: "2–3 days",
    travel_time: "1.5 hours (flight)",
    best_season: ["summer", "spring"],
    interests: ["nightlife", "culture", "food", "history"],
    vibe: ["social", "energetic"],
    travel_style: ["group-friendly", "adventure"],
    priorities: ["best-nightlife", "best-food", "social"],
    weather: ["cool", "variable"],
    student_tip: "Book Temple Bar early - it fills up fast. Guinness Storehouse is worth the entry for the views.",
    highlights: ["Temple Bar", "Trinity College", "Guinness Storehouse", "Pubs"],
    testimonial_source: "Group Travel Favorite"
  },

  {
    id: "prague",
    name: "Prague",
    country: "Czech Republic",
    coordinates: [14.4370, 50.0755],
    marker_emoji: "🏰",
    image_url: "https://images.unsplash.com/photo-1508525059616-e83985b0acf0?w=400&h=300&fit=crop",
    description: "Medieval fairytale city - stunning architecture and very cheap.",
    budget: "budget",
    estimated_cost: "£50–100",
    duration_category: "weekend",
    duration_label: "2–3 days",
    travel_time: "2 hours (flight)",
    best_season: ["spring", "fall"],
    interests: ["history", "architecture", "food", "culture"],
    vibe: ["romantic", "cultural"],
    travel_style: ["budget-friendly", "cultural"],
    priorities: ["best-budget", "romantic", "easy-to-get-around"],
    weather: ["mild", "pleasant"],
    student_tip: "Czech beer is incredibly cheap - enjoy it! Avoid Old Town Square restaurants, head to side streets.",
    highlights: ["Charles Bridge", "Prague Castle", "Old Town Square", "Beer Halls"],
    testimonial_source: "Jamal & Liv"
  },

  {
    id: "budapest",
    name: "Budapest",
    country: "Hungary",
    coordinates: [19.0402, 47.4979],
    marker_emoji: "🛁",
    image_url: "https://images.unsplash.com/photo-1570129477492-45ec003d2720?w=400&h=300&fit=crop",
    description: "Thermal baths and ruin bars - perfect for a fun, affordable weekend.",
    budget: "budget",
    estimated_cost: "£50–110",
    duration_category: "weekend",
    duration_label: "2–3 days",
    travel_time: "2.5 hours (flight)",
    best_season: ["spring", "summer", "fall"],
    interests: ["nightlife", "relaxation", "culture", "food"],
    vibe: ["social", "relaxed"],
    travel_style: ["group-friendly", "wellness"],
    priorities: ["best-nightlife", "best-value", "social"],
    weather: ["warm", "pleasant"],
    student_tip: "Ruin bars are iconic - extremely social. Thermal baths are therapeutic and cheap.",
    highlights: ["Thermal Baths", "Ruin Bars", "Danube River", "Street Food"],
    testimonial_source: "Aiden & Kai"
  },

  {
    id: "krakow",
    name: "Kraków",
    country: "Poland",
    coordinates: [19.9450, 50.0647],
    marker_emoji: "⛓️",
    image_url: "https://images.unsplash.com/photo-1549862596-bdf5c7764e5e?w=400&h=300&fit=crop",
    description: "Historic city with medieval charm, proximity to salt mines, and vibrant student scene.",
    budget: "budget",
    estimated_cost: "£40–90",
    duration_category: "weekend",
    duration_label: "2–3 days",
    travel_time: "2.5 hours (flight)",
    best_season: ["spring", "fall"],
    interests: ["history", "culture", "nightlife", "food"],
    vibe: ["cultural", "social"],
    travel_style: ["budget-friendly", "cultural"],
    priorities: ["best-budget", "best-nightlife", "easy-to-get-around"],
    weather: ["cool", "pleasant"],
    student_tip: "Kazimierz is the heart of student nightlife. The salt mines are a unique day trip.",
    highlights: ["Main Square", "Kazimierz District", "Salt Mines", "Street Food"],
    testimonial_source: "Polish Adventure"
  },

  {
    id: "edinburgh",
    name: "Edinburgh",
    country: "Scotland",
    coordinates: [-3.1883, 55.9533],
    marker_emoji: "🥃",
    image_url: "https://images.unsplash.com/photo-1506905925346-21bda4d32df4?w=400&h=300&fit=crop",
    description: "Medieval castles, cobbled streets, and stunning Scottish views.",
    budget: "moderate",
    estimated_cost: "£50–100",
    duration_category: "weekend",
    duration_label: "2–3 days",
    travel_time: "2 hours (flight or train)",
    best_season: ["summer", "fall"],
    interests: ["history", "culture", "hiking", "nightlife"],
    vibe: ["cultural", "energetic"],
    travel_style: ["cultural", "adventure"],
    priorities: ["best-views", "easy-to-get-around", "romantic"],
    weather: ["cool", "variable"],
    student_tip: "Stay in the city center for access to everything. The walk up to Edinburgh Castle is worth the effort.",
    highlights: ["Edinburgh Castle", "Royal Mile", "Holyrood Park", "Nightlife"],
    testimonial_source: "UK Trip Favorite"
  },

  {
    id: "malta",
    name: "Malta",
    country: "Malta",
    coordinates: [14.5898, 35.9375],
    marker_emoji: "🌊",
    image_url: "https://images.unsplash.com/photo-1570129476503-ccf17ce24ddf?w=400&h=300&fit=crop",
    description: "Ancient ruins, turquoise water, and Mediterranean charm in a tiny island nation.",
    budget: "moderate",
    estimated_cost: "£70–140",
    duration_category: "weekend",
    duration_label: "2–3 days",
    travel_time: "2.5 hours (flight)",
    best_season: ["spring", "summer", "fall"],
    interests: ["history", "beach", "culture", "diving"],
    vibe: ["relaxed", "social"],
    travel_style: ["adventure", "chill"],
    priorities: ["best-beach", "best-history", "easy-to-get-around"],
    weather: ["warm", "sunny"],
    student_tip: "Valletta is the historic capital. The tiny size means everything is walkable. Great diving spot.",
    highlights: ["Valletta", "Blue Lagoon", "Ancient Temples", "Diving"],
    testimonial_source: "Mediterranean Gem"
  },

  // ============ BEACH & WARM WEATHER TRIPS ============
  {
    id: "barcelona",
    name: "Barcelona",
    country: "Spain",
    coordinates: [2.1729, 41.3851],
    marker_emoji: "🏖️",
    image_url: "https://images.unsplash.com/photo-1583422409516-2895a77efded?w=400&h=300&fit=crop",
    description: "Beach, architecture, and vibrant culture - perfect for spring/summer.",
    budget: "moderate",
    estimated_cost: "£100–180",
    duration_category: "extended",
    duration_label: "3–4 days",
    travel_time: "2 hours (flight)",
    best_season: ["spring", "summer", "fall"],
    interests: ["beach", "architecture", "food", "culture"],
    vibe: ["energetic", "social"],
    travel_style: ["group-friendly", "adventure"],
    priorities: ["best-food", "best-nightlife", "easy-to-get-around"],
    weather: ["warm", "sunny"],
    student_tip: "Visit Sagrada Familia early or buy skip-the-line tickets. Beachfront drinks are pricier than city center.",
    highlights: ["Sagrada Familia", "Park Güell", "Beach", "Tapas"],
    testimonial_source: "Zara & Marcus"
  },

  {
    id: "madrid",
    name: "Madrid",
    country: "Spain",
    coordinates: [-3.7038, 40.4168],
    marker_emoji: "🎨",
    image_url: "https://images.unsplash.com/photo-1577720643272-265f434f4623?w=400&h=300&fit=crop",
    description: "Spain's energetic capital - world-class museums, tapas, and late-night vibes.",
    budget: "moderate",
    estimated_cost: "£70–140",
    duration_category: "extended",
    duration_label: "2–3 days",
    travel_time: "2 hours (flight)",
    best_season: ["spring", "fall"],
    interests: ["food", "art", "nightlife", "culture"],
    vibe: ["energetic", "social"],
    travel_style: ["group-friendly", "food-focused"],
    priorities: ["best-museums", "best-nightlife", "best-food"],
    weather: ["warm", "sunny"],
    student_tip: "Dinner starts late (9pm+). Free museum hours are 6–8pm weekdays. Tapas crawl in La Latina.",
    highlights: ["Prado Museum", "La Latina", "Retiro Park", "Tapas Bars"],
    testimonial_source: "Spain's Capital"
  },

  {
    id: "lisbon",
    name: "Lisbon",
    country: "Portugal",
    coordinates: [-9.1393, 38.7223],
    marker_emoji: "☀️",
    image_url: "https://images.unsplash.com/photo-1610295867412-82589a67fb0b?w=400&h=300&fit=crop",
    description: "Warm weather, friendly locals, and great food - Portugal's coolest city.",
    budget: "budget",
    estimated_cost: "£60–120",
    duration_category: "extended",
    duration_label: "3 days",
    travel_time: "3 hours (flight)",
    best_season: ["spring", "summer", "fall"],
    interests: ["beach", "food", "culture", "relaxation"],
    vibe: ["relaxed", "social"],
    travel_style: ["budget-friendly", "chill"],
    priorities: ["best-food", "best-weather", "budget"],
    weather: ["warm", "sunny"],
    student_tip: "Pastel de Nata and cheap wine everywhere. The city is very walkable and affordable.",
    highlights: ["Belém Tower", "Street Food", "Fado Music", "Beaches"],
    testimonial_source: "Emma & Nia"
  },

  {
    id: "porto",
    name: "Porto",
    country: "Portugal",
    coordinates: [-8.6291, 41.1579],
    marker_emoji: "🍷",
    image_url: "https://images.unsplash.com/photo-1555881286-0e8d1c38dbc2?w=400&h=300&fit=crop",
    description: "Portugal's hidden gem - riverside charm, Port wine, and historic neighborhoods.",
    budget: "budget",
    estimated_cost: "£50–100",
    duration_category: "weekend",
    duration_label: "2–3 days",
    travel_time: "3.5 hours (flight)",
    best_season: ["spring", "summer", "fall"],
    interests: ["food", "culture", "relaxation", "wine"],
    vibe: ["relaxed", "cultural"],
    travel_style: ["budget-friendly", "chill"],
    priorities: ["best-food", "best-value", "easy-to-get-around"],
    weather: ["warm", "pleasant"],
    student_tip: "Stay in Ribeira for authentic vibes. Port wine tastings are a must - find affordable tasting rooms.",
    highlights: ["Ribeira District", "Dom Luís Bridge", "Port Wine", "River Cruises"],
    testimonial_source: "Hidden Gem"
  },

  {
    id: "valencia",
    name: "Valencia",
    country: "Spain",
    coordinates: [-0.3763, 39.4699],
    marker_emoji: "🥘",
    image_url: "https://images.unsplash.com/photo-1611394767303-c69f3d855744?w=400&h=300&fit=crop",
    description: "Beach vibes with futuristic architecture, paella, and less touristy than Barcelona.",
    budget: "moderate",
    estimated_cost: "£70–130",
    duration_category: "extended",
    duration_label: "2–3 days",
    travel_time: "2.5 hours (flight)",
    best_season: ["spring", "summer", "fall"],
    interests: ["beach", "architecture", "food", "culture"],
    vibe: ["energetic", "relaxed"],
    travel_style: ["group-friendly", "food-focused"],
    priorities: ["best-food", "best-beach", "easy-to-get-around"],
    weather: ["warm", "sunny"],
    student_tip: "City of Arts and Sciences is stunning. Paella is authentic here and way cheaper than tourist spots.",
    highlights: ["City of Arts & Sciences", "Beach", "Paella", "Las Fallas (March)"],
    testimonial_source: "Beach Alternative"
  },

  {
    id: "mallorca",
    name: "Mallorca",
    country: "Spain",
    coordinates: [2.7500, 39.5500],
    marker_emoji: "🏝️",
    image_url: "https://images.unsplash.com/photo-1559827260-dc66d52bef19?w=400&h=300&fit=crop",
    description: "Balearic island perfection - beaches, mountain views, and party culture.",
    budget: "moderate",
    estimated_cost: "£100–180",
    duration_category: "extended",
    duration_label: "3–4 days",
    travel_time: "2 hours (flight)",
    best_season: ["summer"],
    interests: ["beach", "nightlife", "food", "nature"],
    vibe: ["energetic", "social"],
    travel_style: ["group-friendly", "adventure"],
    priorities: ["best-nightlife", "best-beach", "social"],
    weather: ["warm", "sunny"],
    student_tip: "Avoid Magaluf if you want authentic vibes. Palma is way better for culture and food.",
    highlights: ["Beaches", "Nightlife", "Mountain Hikes", "Fresh Seafood"],
    testimonial_source: "Island Paradise"
  },

  {
    id: "tenerife",
    name: "Tenerife",
    country: "Spain (Canary Islands)",
    coordinates: [-16.3387, 28.2916],
    marker_emoji: "🌋",
    image_url: "https://images.unsplash.com/photo-1507525428034-b723cf961d3e?w=400&h=300&fit=crop",
    description: "Canary Islands sunshine - beaches, volcanic landscape, and eternal summer.",
    budget: "moderate",
    estimated_cost: "£80–150",
    duration_category: "extended",
    duration_label: "3–5 days",
    travel_time: "4 hours (flight)",
    best_season: ["spring", "summer", "fall"],
    interests: ["beach", "hiking", "relaxation", "nature"],
    vibe: ["relaxed", "energetic"],
    travel_style: ["adventure", "chill"],
    priorities: ["best-weather", "best-beach", "best-value"],
    weather: ["warm", "sunny"],
    student_tip: "Climb Mount Teide at sunrise. Northern beaches are less touristy and cheaper than southern ones.",
    highlights: ["Mount Teide", "Black Sand Beaches", "Hiking", "Whale Watching"],
    testimonial_source: "Island Escape"
  },

  {
    id: "nice",
    name: "Nice",
    country: "France",
    coordinates: [7.2620, 43.7102],
    marker_emoji: "🌴",
    image_url: "https://images.unsplash.com/photo-1488646953014-85cb44e25828?w=400&h=300&fit=crop",
    description: "French Riviera elegance - beaches, promenade, and art scene.",
    budget: "expensive",
    estimated_cost: "£90–160",
    duration_category: "weekend",
    duration_label: "2–3 days",
    travel_time: "2.5 hours (flight)",
    best_season: ["spring", "summer", "fall"],
    interests: ["beach", "art", "food", "relaxation"],
    vibe: ["relaxed", "cultural"],
    travel_style: ["food-focused", "chill"],
    priorities: ["best-beach", "best-food", "best-views"],
    weather: ["warm", "sunny"],
    student_tip: "Promenade des Anglais is perfect for people-watching. Explore the Old Town for authentic restaurants.",
    highlights: ["Promenade des Anglais", "Old Town", "Beaches", "Art Museums"],
    testimonial_source: "Riviera Escape"
  },

  // ============ MOUNTAIN & SCENIC ADVENTURES ============
  {
    id: "interlaken",
    name: "Interlaken",
    country: "Switzerland",
    coordinates: [8.1792, 46.6863],
    marker_emoji: "⛰️",
    image_url: "https://images.unsplash.com/photo-1549655069-4cc69754b298?w=400&h=300&fit=crop",
    description: "Alpine paradise - mountain hikes, adventure sports, and jaw-dropping views.",
    budget: "expensive",
    estimated_cost: "£120–220",
    duration_category: "extended",
    duration_label: "2–3 days",
    travel_time: "2.5 hours (flight/train)",
    best_season: ["summer", "fall"],
    interests: ["hiking", "adventure", "nature", "mountain"],
    vibe: ["adventurous", "energetic"],
    travel_style: ["adventure", "nature"],
    priorities: ["best-views", "best-hiking", "adventure"],
    weather: ["cool", "pleasant"],
    student_tip: "Book the Jungfrau train in advance for discounts. Budget hostels here are still pricey but worth it.",
    highlights: ["Jungfrau", "Mountain Hikes", "Adventure Sports", "Swiss Lakes"],
    testimonial_source: "Mountain Adventure"
  },

  {
    id: "lake-bled",
    name: "Lake Bled",
    country: "Slovenia",
    coordinates: [14.1122, 46.3625],
    marker_emoji: "💙",
    image_url: "https://images.unsplash.com/photo-1507003211169-0a1dd7228f2d?w=400&h=300&fit=crop",
    description: "Stunning lake with island church - Slovenia's most romantic destination.",
    budget: "budget",
    estimated_cost: "£50–100",
    duration_category: "weekend",
    duration_label: "2–3 days",
    travel_time: "2 hours (flight)",
    best_season: ["summer", "spring"],
    interests: ["nature", "hiking", "romance", "relaxation"],
    vibe: ["relaxed", "romantic"],
    travel_style: ["chill", "nature"],
    priorities: ["best-views", "romantic", "budget"],
    weather: ["warm", "pleasant"],
    student_tip: "Row out to Bled Island in a traditional boat. The viewpoint hike is free and stunning.",
    highlights: ["Bled Island", "Castle Viewpoint", "Lake Hikes", "Cream Cake"],
    testimonial_source: "Hidden Gem"
  },

  {
    id: "dolomites",
    name: "Dolomites",
    country: "Italy",
    coordinates: [11.8500, 46.3000],
    marker_emoji: "🏔️",
    image_url: "https://images.unsplash.com/photo-1506905925346-21bda4d32df4?w=400&h=300&fit=crop",
    description: "Dramatic mountain scenery - world-class hiking and postcard-perfect villages.",
    budget: "expensive",
    estimated_cost: "£100–180",
    duration_category: "extended",
    duration_label: "3–4 days",
    travel_time: "3 hours (flight)",
    best_season: ["summer", "fall"],
    interests: ["hiking", "nature", "mountain", "adventure"],
    vibe: ["adventurous", "energetic"],
    travel_style: ["adventure", "nature"],
    priorities: ["best-hiking", "best-views", "adventure"],
    weather: ["cool", "pleasant"],
    student_tip: "Book accommodation in villages like Cortina. Hiking the Tre Cime is iconic and worth it.",
    highlights: ["Tre Cime", "Mountain Hikes", "Alpine Villages", "Alpine Lakes"],
    testimonial_source: "Mountain Paradise"
  },

  {
    id: "cinque-terre",
    name: "Cinque Terre",
    country: "Italy",
    coordinates: [9.6833, 43.1333],
    marker_emoji: "🌅",
    image_url: "https://images.unsplash.com/photo-1524850011238-e3d235e843d3?w=400&h=300&fit=crop",
    description: "Five colorful cliff-hanging villages - UNESCO wonder and Italy's best hiking.",
    budget: "moderate",
    estimated_cost: "£80–150",
    duration_category: "extended",
    duration_label: "2–3 days",
    travel_time: "2.5 hours (flight/train)",
    best_season: ["spring", "summer", "fall"],
    interests: ["hiking", "nature", "food", "beach"],
    vibe: ["adventurous", "relaxed"],
    travel_style: ["adventure", "nature"],
    priorities: ["best-hiking", "best-views", "easy-to-get-around"],
    weather: ["warm", "pleasant"],
    student_tip: "Buy a 5-day Cinque Terre card for trains and trails. Stay in one village and day-hop by train.",
    highlights: ["Coastal Hikes", "Colorful Villages", "Fresh Seafood", "Swimming"],
    testimonial_source: "Italian Gem"
  },

  // ============ HISTORIC & CULTURE DESTINATIONS ============
  {
    id: "rome",
    name: "Rome",
    country: "Italy",
    coordinates: [12.4964, 41.9028],
    marker_emoji: "🏛️",
    image_url: "https://images.unsplash.com/photo-1552832230-9f0ee8e2f5c4?w=400&h=300&fit=crop",
    description: "Ancient history and amazing food - the ultimate student bucket list.",
    budget: "moderate",
    estimated_cost: "£90–160",
    duration_category: "extended",
    duration_label: "3–4 days",
    travel_time: "2.5 hours (flight)",
    best_season: ["spring", "fall"],
    interests: ["history", "food", "culture", "architecture"],
    vibe: ["historic", "cultural"],
    travel_style: ["cultural", "food-focused"],
    priorities: ["best-food", "best-museums", "romantic"],
    weather: ["warm", "pleasant"],
    student_tip: "Get the Roma Pass for museum entry. Street food (panini, pizza al taglio) is affordable.",
    highlights: ["Colosseum", "Vatican", "Roman Forum", "Gelato"],
    testimonial_source: "Marcus & Diego"
  },

  {
    id: "berlin",
    name: "Berlin",
    country: "Germany",
    coordinates: [13.4050, 52.5200],
    marker_emoji: "🎭",
    image_url: "https://images.unsplash.com/photo-1552365434-dfffc6d95ce9?w=400&h=300&fit=crop",
    description: "History, street art, and legendary nightlife - very affordable.",
    budget: "budget",
    estimated_cost: "£60–120",
    duration_category: "extended",
    duration_label: "3 days",
    travel_time: "1.5 hours (flight)",
    best_season: ["spring", "fall"],
    interests: ["history", "nightlife", "art", "culture"],
    vibe: ["artsy", "social"],
    travel_style: ["budget-friendly", "cultural"],
    priorities: ["best-nightlife", "best-art-scene", "budget"],
    weather: ["cool", "pleasant"],
    student_tip: "Berlin is super affordable. Visit museums on free entry evenings. Kreuzberg has the best street art.",
    highlights: ["Brandenburg Gate", "Street Art", "Nightclubs", "Museums"],
    testimonial_source: "Sarah & Aiden"
  },

  {
    id: "vienna",
    name: "Vienna",
    country: "Austria",
    coordinates: [16.3738, 48.2082],
    marker_emoji: "🎼",
    image_url: "https://images.unsplash.com/photo-1516941510602-a79898e9de4d?w=400&h=300&fit=crop",
    description: "Imperial palaces, classical music, and elegant Austro-Hungarian architecture.",
    budget: "moderate",
    estimated_cost: "£60–120",
    duration_category: "extended",
    duration_label: "2–3 days",
    travel_time: "2.5 hours (flight)",
    best_season: ["spring", "fall"],
    interests: ["culture", "history", "food", "art"],
    vibe: ["cultural", "romantic"],
    travel_style: ["cultural", "food-focused"],
    priorities: ["best-museums", "romantic", "best-food"],
    weather: ["mild", "pleasant"],
    student_tip: "Get a Vienna City Card for free transport and museum discounts. Coffee culture is huge here.",
    highlights: ["Schönbrunn Palace", "St. Stephen's Cathedral", "Opera House", "Cafés"],
    testimonial_source: "Austria Visit"
  },

  {
    id: "copenhagen",
    name: "Copenhagen",
    country: "Denmark",
    coordinates: [12.5683, 55.6761],
    marker_emoji: "🚴",
    image_url: "https://images.unsplash.com/photo-1513635269975-59663e0ac1ad?w=400&h=300&fit=crop",
    description: "Hygge vibes, colorful Nyhavn harbor, and cool Scandinavian design scene.",
    budget: "expensive",
    estimated_cost: "£70–150",
    duration_category: "weekend",
    duration_label: "2–3 days",
    travel_time: "1.5 hours (flight)",
    best_season: ["summer", "spring"],
    interests: ["design", "food", "nightlife", "culture"],
    vibe: ["social", "trendy"],
    travel_style: ["group-friendly", "adventure"],
    priorities: ["best-design", "best-food", "easy-to-get-around"],
    weather: ["cool", "pleasant"],
    student_tip: "Copenhagen is pricey but worth it. Bikes are the main transport. Visit Nyhavn at sunset.",
    highlights: ["Nyhavn Harbor", "Tivoli Gardens", "Street Food", "Design Scene"],
    testimonial_source: "Nordic Trip"
  },

  // ============ HIDDEN GEMS & UNIQUE DESTINATIONS ============
  {
    id: "chefchaouen",
    name: "Chefchaouen",
    country: "Morocco",
    coordinates: [-5.2698, 35.1684],
    marker_emoji: "🔵",
    image_url: "https://images.unsplash.com/photo-1549926586-80f7fbdd1e6d?w=400&h=300&fit=crop",
    description: "Morocco's blue city - stunning Rif mountain scenery, culture, and adventure.",
    budget: "budget",
    estimated_cost: "£40–80",
    duration_category: "extended",
    duration_label: "3–4 days",
    travel_time: "3.5 hours (flight to Fez + transport)",
    best_season: ["spring", "fall"],
    interests: ["culture", "photography", "hiking", "adventure"],
    vibe: ["adventurous", "cultural"],
    travel_style: ["adventure", "cultural"],
    priorities: ["best-views", "best-budget", "adventure"],
    weather: ["warm", "pleasant"],
    student_tip: "Take the bus from Fez - it's an adventure in itself. Stay in a riad for authentic experiences.",
    highlights: ["Blue City Streets", "Rif Mountains", "Waterfalls", "Local Markets"],
    testimonial_source: "North Africa Adventure"
  },

  {
    id: "marrakech",
    name: "Marrakech",
    country: "Morocco",
    coordinates: [-8.0029, 31.6295],
    marker_emoji: "🌙",
    image_url: "https://images.unsplash.com/photo-1549926586-80f7fbdd1e6d?w=400&h=300&fit=crop",
    description: "Morocco's magic city - bustling medinas, palaces, and Sahara desert access.",
    budget: "budget",
    estimated_cost: "£50–100",
    duration_category: "extended",
    duration_label: "3–4 days",
    travel_time: "3.5 hours (flight)",
    best_season: ["spring", "fall"],
    interests: ["culture", "food", "history", "adventure"],
    vibe: ["energetic", "cultural"],
    travel_style: ["adventure", "cultural", "food-focused"],
    priorities: ["best-culture", "best-budget", "adventure"],
    weather: ["warm", "sunny"],
    student_tip: "Jemaa el-Fnaa square is chaotic but essential. Take a day trip to the Atlas Mountains or Sahara.",
    highlights: ["Medina", "Jemaa el-Fnaa", "Palaces", "Atlas Mountains"],
    testimonial_source: "Morocco Escape"
  }
];

// ============================================================
// COLOR & EMOJI MAPPING FOR FILTERS
// ============================================================

const budgetColors = {
  "budget": "#2ecc71",
  "moderate": "#f39c12",
  "expensive": "#e74c3c"
};

const vibeEmojis = {
  "romantic": "💕",
  "social": "🎉",
  "energetic": "⚡",
  "artsy": "🎨",
  "historic": "📚",
  "relaxed": "😌",
  "cultural": "🌍",
  "adventurous": "🧗",
  "trendy": "✨"
};

// ============================================================
// STUDENT TESTIMONIALS
// ============================================================

const studentTestimonials = [
  {
    id: 1,
    name: "Sarah",
    year: "Junior",
    destination_id: ["paris", "berlin"],
    text: "Paris was dreamy but can get pricey. Berlin blew my mind with the nightlife and art scene!",
    image: "👩"
  },
  {
    id: 2,
    name: "Marcus",
    year: "Sophomore",
    destination_id: ["paris", "barcelona", "rome"],
    text: "I've done three European trips. Pro tip: visit museums early morning to avoid crowds and save money.",
    image: "👨"
  },
  {
    id: 3,
    name: "Emma",
    year: "Junior",
    destination_id: ["amsterdam", "lisbon"],
    text: "Amsterdam was perfect for a friend group trip. Lisbon was unexpectedly relaxing - great vibes.",
    image: "👩"
  },
  {
    id: 4,
    name: "Jamal",
    year: "Senior",
    destination_id: ["amsterdam", "prague"],
    text: "Prague is unbelievably cheap. I saved money there to splurge in Amsterdam. Both worth it!",
    image: "👨"
  },
  {
    id: 5,
    name: "Zara",
    year: "Junior",
    destination_id: ["barcelona"],
    text: "Barcelona was my favorite. Went for the beaches, stayed for the food. Paella was life-changing.",
    image: "👩"
  },
  {
    id: 6,
    name: "Aiden",
    year: "Sophomore",
    destination_id: ["berlin", "budapest"],
    text: "Berlin's nightlife is unmatched. Budapest's ruin bars are the best social experience ever.",
    image: "👨"
  },
  {
    id: 7,
    name: "Liv",
    year: "Senior",
    destination_id: ["prague"],
    text: "Prague felt like stepping into a fairy tale. Cheapest beer I've ever had. Highly recommend!",
    image: "👩"
  },
  {
    id: 8,
    name: "Diego",
    year: "Junior",
    destination_id: ["rome"],
    text: "Rome is pricey but worth every penny. The history and food are incredible. Go for at least 3 days.",
    image: "👨"
  },
  {
    id: 9,
    name: "Nia",
    year: "Sophomore",
    destination_id: ["lisbon"],
    text: "Lisbon was affordable and chill. Perfect place to slow down and enjoy good food and weather.",
    image: "👩"
  },
  {
    id: 10,
    name: "Kai",
    year: "Junior",
    destination_id: ["budapest"],
    text: "The thermal baths in Budapest are therapeutic. Ruin bars are where students go to party. Amazing experience!",
    image: "👨"
  }
];
